# Generated by Django 4.0.5 on 2022-07-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_img_post_price_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('Owner', 'Ownerfffff'), ('Organization', 'Organization')], max_length=100),
        ),
    ]
