# Generated by Django 4.0.5 on 2022-07-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Organization', 'Organization')], max_length=100),
        ),
    ]
