# Generated by Django 4.0.5 on 2022-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, choices=[('For sale', 'For sale'), ('Giveaway', 'Giveaway'), ('Wanted', 'Wanted'), ('Exchange', 'Exchange')], max_length=100),
        ),
    ]
