# Generated by Django 4.0.5 on 2022-07-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, choices=[('Yerevan', 'Yerevan'), ('Lori', 'Lori'), ('Tavush', 'Tavush'), ('Armavir', 'Armavir')], max_length=100),
        ),
    ]
